# -*- coding: utf-8 -*-
"""Miniprojectfinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZkP4j2PPdydlNdEi42Cz0i37BFqqKPT4
"""

from google.colab import drive
drive.mount('/content/drive')

DATASET_PATH = "/content/drive/MyDrive/Watch_Guard_ds"

import os

DATASET_PATH ="/content/drive/MyDrive/Watch_Gaurd_ds"

for root, dirs, files in os.walk(DATASET_PATH):
    print("📁 Folder:", root)
    print("📂 Subfolders:", dirs)
    print("🖼 Files:", len(files))
    print("-"*40)

import os

base = "/content/drive/MyDrive/Watch_Gaurd_ds"

print("Folders inside dataset:")
print(os.listdir(base))

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    if "masked" in dirs:
        print("Found at:", os.path.join(root, "masked"))

import os
import random
import shutil

# Paths
main_dir = "/content/drive/MyDrive/Watch_Gaurd_ds"
masked_dir = "/content/drive/MyDrive/reduced_dataset/masked"
output_dir = "/content/drive/MyDrive/balanced_200_dataset"

# Clean output
if os.path.exists(output_dir):
    shutil.rmtree(output_dir)
os.makedirs(output_dir)

# Classes
classes = ["anomaly", "normal", "theft"]

# Process main classes
for cls in classes:
    src = os.path.join(main_dir, cls)
    dst = os.path.join(output_dir, cls)
    os.makedirs(dst)

    files = os.listdir(src)

    if len(files) < 200:
        print(f"⚠️ {cls} has only {len(files)} samples")
        continue

    sampled = random.sample(files, 200)

    for f in sampled:
        shutil.copy(os.path.join(src, f), os.path.join(dst, f))

# ✅ Add masked separately
dst = os.path.join(output_dir, "masked")
os.makedirs(dst)

files = os.listdir(masked_dir)

if len(files) < 200:
    print(f"⚠️ masked has only {len(files)} samples")
else:
    sampled = random.sample(files, 200)

    for f in sampled:
        shutil.copy(os.path.join(masked_dir, f), os.path.join(dst, f))

print("✅ All 4 classes created successfully!")

for cls in os.listdir(output_dir):
    print(cls, len(os.listdir(os.path.join(output_dir, cls))))

import os
import random
import shutil

input_dir = "/content/drive/MyDrive/balanced_200_dataset"
output_dir = "/content/drive/MyDrive/split_dataset"

# Clean output
if os.path.exists(output_dir):
    shutil.rmtree(output_dir)
os.makedirs(output_dir)

splits = ["train", "val", "test"]
for split in splits:
    os.makedirs(os.path.join(output_dir, split))

classes = os.listdir(input_dir)

for cls in classes:
    cls_path = os.path.join(input_dir, cls)
    files = os.listdir(cls_path)

    random.shuffle(files)

    train_files = files[:140]
    val_files = files[140:170]
    test_files = files[170:200]

    for split_name, split_files in zip(
        ["train", "val", "test"],
        [train_files, val_files, test_files]
    ):
        split_cls_path = os.path.join(output_dir, split_name, cls)
        os.makedirs(split_cls_path)

        for f in split_files:
            shutil.copy(
                os.path.join(cls_path, f),
                os.path.join(split_cls_path, f)
            )

print("✅ Dataset split complete!")

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt

data_dir = "/content/drive/MyDrive/split_dataset"

train_dir = data_dir + "/train"
val_dir   = data_dir + "/val"
test_dir  = data_dir + "/test"

# 🔄 Transforms
transform_train = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ColorJitter(brightness=0.2),
    transforms.ToTensor(),
])

transform_val_test = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
])

train_data = datasets.ImageFolder(train_dir, transform=transform_train)
val_data   = datasets.ImageFolder(val_dir, transform=transform_val_test)
test_data  = datasets.ImageFolder(test_dir, transform=transform_val_test)

train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
val_loader   = DataLoader(val_data, batch_size=32, shuffle=False)
test_loader  = DataLoader(test_data, batch_size=32, shuffle=False)

print("Classes:", train_data.classes)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

from torchvision import models

# Load pretrained ResNet18
model = models.resnet18(pretrained=True)

# Freeze all layers
for param in model.parameters():
    param.requires_grad = False

for param in model.fc.parameters():
    param.requires_grad = True

# Replace final layer for 4 classes
model.fc = nn.Linear(model.fc.in_features, 4)

# Move to device
model = model.to(device)

# Loss
criterion = nn.CrossEntropyLoss()

# Optimizer (ONLY train final layer)
optimizer = optim.Adam(model.fc.parameters(), lr=0.001)

epochs = 10

for epoch in range(epochs):
    model.train()
    running_loss = 0
    correct = 0
    total = 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    train_acc = 100 * correct / total

    # Validation
    model.eval()
    val_correct = 0
    val_total = 0

    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)

            _, predicted = torch.max(outputs, 1)
            val_total += labels.size(0)
            val_correct += (predicted == labels).sum().item()

    val_acc = 100 * val_correct / val_total

    print(f"Epoch {epoch+1}: Loss={running_loss:.4f}, Train Acc={train_acc:.2f}%, Val Acc={val_acc:.2f}%")

model.eval()
correct = 0
total = 0

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)

        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f"Test Accuracy: {100 * correct / total:.2f}%")

torch.save(model.state_dict(), "resnet_model.pth")

!pip install scikit-learn

import torch
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

model.eval()

all_preds = []
all_labels = []

with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)
        _, preds = torch.max(outputs, 1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

cm = confusion_matrix(all_labels, all_preds)

plt.figure()
sns.heatmap(cm, annot=True, fmt='d',
            xticklabels=train_data.classes,
            yticklabels=train_data.classes)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

print(classification_report(all_labels, all_preds, target_names=train_data.classes))

import os

print(os.listdir("/content/drive/MyDrive"))

torch.save(model.state_dict(), "/content/drive/MyDrive/resnet_model.pth")

import torch
from PIL import Image
from torchvision import transforms

# Load model
model.load_state_dict(torch.load("/content/drive/MyDrive/resnet_model.pth"))
model.eval()

# Class names (IMPORTANT: same order as training)
class_names = train_data.classes
print(class_names)

# Transform (same as val/test)
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
])

def predict_image(image_path):
    image = Image.open(image_path).convert("RGB")
    image = transform(image).unsqueeze(0).to(device)

    with torch.no_grad():
        outputs = model(image)
        _, predicted = torch.max(outputs, 1)

    return class_names[predicted.item()]

img_path = "/content/drive/MyDrive/test_image1.jpg"
print("Prediction:", predict_image(img_path))

from google.colab.patches import cv2_imshow

import cv2
from google.colab.patches import cv2_imshow

video_path = "/content/drive/MyDrive/TestVideo.mp4"
cap = cv2.VideoCapture(video_path)

frame_count = 0

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    label = predict_frame(frame)

    # Put label
    cv2.putText(frame, label, (20, 40),
                cv2.FONT_HERSHEY_SIMPLEX,
                1, (0,255,0), 2)

    cv2_imshow(frame)

    frame_count += 1
    if frame_count > 50:   # limit frames (VERY IMPORTANT ⚠️)
        break

cap.release()

import cv2
from collections import Counter

video_path = "/content/drive/MyDrive/Test2.mp4"
cap = cv2.VideoCapture(video_path)

predictions = []

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    label = predict_frame(frame)
    predictions.append(label)

cap.release()

# Get final prediction
final_prediction = Counter(predictions).most_common(1)[0][0]

print("🎥 Final Video Prediction:", final_prediction)

from collections import Counter

counts = Counter(predictions)

print("Frame-wise prediction counts:")
for k, v in counts.items():
    print(f"{k}: {v}")

!ls /content/drive/MyDrive

!ls /content

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import torch
# import torch.nn as nn
# from torchvision import transforms, models
# from PIL import Image
# import cv2
# from collections import Counter
# import tempfile
# 
# # ------------------ DEVICE ------------------
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 
# # ------------------ LOAD MODEL ------------------
# model = models.resnet18(pretrained=False)
# model.fc = nn.Linear(model.fc.in_features, 4)
# 
# model.load_state_dict(torch.load("resnet_model.pth", map_location=device))
# model = model.to(device)
# model.eval()
# 
# class_names = ['anomaly', 'masked', 'normal', 'theft']
# 
# # ------------------ TRANSFORM ------------------
# transform = transforms.Compose([
#     transforms.Resize((224, 224)),
#     transforms.ToTensor(),
# ])
# 
# # ------------------ IMAGE PREDICTION ------------------
# def predict_image(image):
#     image = transform(image).unsqueeze(0).to(device)
#     with torch.no_grad():
#         outputs = model(image)
#         _, pred = torch.max(outputs, 1)
#     return class_names[pred.item()]
# 
# # ------------------ VIDEO PREDICTION ------------------
# def predict_video(video_file):
#     tfile = tempfile.NamedTemporaryFile(delete=False)
#     tfile.write(video_file.read())
# 
#     cap = cv2.VideoCapture(tfile.name)
#     predictions = []
# 
#     while cap.isOpened():
#         ret, frame = cap.read()
#         if not ret:
#             break
# 
#         image = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
#         label = predict_image(image)
#         predictions.append(label)
# 
#     cap.release()
# 
#     final_pred = Counter(predictions).most_common(1)[0][0]
#     return final_pred
# 
# # ------------------ UI ------------------
# st.title("🔍 Surveillance Detection App")
# 
# option = st.radio("Choose input type:", ["Image", "Video"])
# 
# if option == "Image":
#     uploaded_file = st.file_uploader("Upload Image", type=["jpg", "png", "jpeg"])
# 
#     if uploaded_file:
#         image = Image.open(uploaded_file)
#         st.image(image, caption="Uploaded Image", use_column_width=True)
# 
#         result = predict_image(image)
#         st.success(f"Prediction: {result}")
# 
# elif option == "Video":
#     uploaded_file = st.file_uploader("Upload Video", type=["mp4", "avi"])
# 
#     if uploaded_file:
#         st.video(uploaded_file)
# 
#         result = predict_video(uploaded_file)
#         st.success(f"Final Video Prediction: {result}")

!ls

!cp app.py /content/drive/MyDrive/